[sources.syslog_in]
type = "syslog"
address = "udp://127.0.0.1:5514"

[transforms.sql_enrich]
type = "sql"
inputs = ["syslog_in"]
query = "SELECT message, COUNT(*) AS total FROM logs GROUP BY message"
error_policy = "clamp"

[transforms.sql_enrich.limits]
max_state_bytes = "32MiB"
max_row_bytes = "16KiB"
max_group_bytes = "512KiB"
cpu_budget_ns_per_sec = "50ms"
late_event_threshold_seconds = 5

[sinks.console]
type = "console"
inputs = ["sql_enrich"]
target = "stdout"
