[sources.syslog_in]
type = "syslog"
address = "udp://127.0.0.1:5514"

[transforms.sql_enrich]
type = "sql"
inputs = ["syslog_in"]
query = "SELECT syslog_severity, message FROM logs WHERE syslog_severity <= 4"

[sinks.console]
type = "console"
inputs = ["sql_enrich"]
target = "stdout"
