[sources.syslog_acl]
type = "syslog"
address = "tcp://127.0.0.1:6515"
transport = "tcp"
allowed_peers = ["10.0.0.0/8"]
flush_partial_on_close = true

[transforms.pass_through]
type = "sql"
inputs = ["syslog_acl"]
query = "SELECT syslog_severity, message FROM logs"

[sinks.console]
type = "console"
inputs = ["pass_through"]
target = "stdout"
