[sources.syslog_rfc3164]
type = "syslog"
address = "udp://127.0.0.1:5518"
parser = "rfc3164"

[transforms.pass_through]
type = "sql"
inputs = ["syslog_rfc3164"]
query = "SELECT syslog_severity, message FROM logs"

[sinks.console]
type = "console"
inputs = ["pass_through"]
target = "stdout"
